### ISSUE TITLE
Requirements and Guide

### ISSUE THREAD

**Issue by mcbovice** [generic-trash/themdem#2]
Hi friend. Do you have a guide and list of requirements for this?

**Comment by ArduinoidIOT** [comment]
Just pass a keystone assembler, a capstone disassembler into an AllPass object and call the object on a disassembled codeblock

**Comment by xFlickerx** [comment]
Hello. I wrote a short script from what you deleted, but I can't apply it to the entire program. Every time I get the same error..
Can you help? What did I do wrong?

> Traceback (most recent call last):
  File "F:\sources\themdem-master\start.py", line 45, in <module>
    insns = allpass(insns, profile=True, profile_sub=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\sources\themdem-master\passes\zero_pass.py", line 14, in __call__
    insns = self.optpass(insns, profile=profile_sub, profile_sub=profile_sub)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\sources\themdem-master\passes\combine_pass.py", line 12, in __call__
    insns = optpass(insns, profile=profile_sub, profile_sub=profile_sub)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\sources\themdem-master\passes\base_pass.py", line 122, in __call__
    substituted = self._substitute_instructions(insns, substitutions, substitutions_singlestep, True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\sources\themdem-master\passes\base_pass.py", line 80, in _substitute_instructions
    if not validate(good, bad):
           ^^^^^^^^^^^^^^^^^^^
  File "F:\sources\themdem-master\passes\validation.py", line 60, in validate
    goodstate = emulate(good)
                ^^^^^^^^^^^^^
  File "F:\sources\themdem-master\passes\validation.py", line 53, in emulate
    emu = setup_unicorn(code)
          ^^^^^^^^^^^^^^^^^^^
  File "F:\sources\themdem-master\passes\validation.py", line 32, in setup_unicorn
    emu.mem_write(ADDRESS, code)
  File "C:\Users\Flicker\AppData\Local\Programs\Python\Python311\Lib\site-packages\unicorn\unicorn.py", line 586, in mem_write
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory write (UC_ERR_WRITE_UNMAPPED)

Here is my script:
[start.zip](https://github.com/user-attachments/files/16324557/start.zip)

**Comment by ArduinoidIOT** [comment]
You can try bypassing the validation by adding return true to the first line of the validate function

**Comment by xFlickerx** [comment]
> You can try bypassing the validation by adding return true to the first line of the validate function


Thanks, this helped :) Now another problem appears... pretty nice operand :D
rep movsd dword ptr es:[ebp - 0x58]
Traceback (most recent call last):
#...
keystone.keystone.KsError: Invalid operand (KS_ERR_ASM_INVALIDOPERAND)
